#pragma once

/// DEFINES
#define MAX_FOCAL_DISTANCE 200
#define MIN_FOCAL_DISTANCE 0

#define MAX_BLUR_RAD 10
#define MIN_BLUR_RAD 1

#define MAX_BLUR_MULTIPLIER 10
#define MIN_BLUR_MULTIPLIER 1.1

#define MAX_GLOW_MULTIPLIER 10
#define MIN_GLOW_MULTIPLIER 1.1

#define MAX_AMBIENT_COLOR 1
#define MIN_AMBIENT_COLOR 0.1

#define MAX_SHININESS 16
#define MIN_SHININESS 2

#define MAX_ROUGHNESS 4
#define MIN_ROUGHNESS 0

#define MAX_METALLICITY 1
#define MIN_METALLICITY 0

#define BULLET_SPEED_MODIFIER 0.005f

#define SCREENWIDTH 512
#define SCREENHEIGHT 512

#define MAX_SHADOW_PASSES 6